### ISSUE TITLE
Can we stop using the word "pedagogy"? 

### ISSUE THREAD

**Issue by patrick-nw** [docker-training/docker-present#21]
I know it seems to be a favorite among Docker folk, but it literally means "leading children", and a better word (if you insist on using fancy words and sounding snooty ;-) ) is "andragogy", which means "leading man", and refers to adult education. 

Details here: 

https://en.wikipedia.org/wiki/Andragogy

![you-keep-using-that-word](https://cloud.githubusercontent.com/assets/15927223/26536852/9df7946e-43ef-11e7-9902-e844e7269ee5.jpeg)

:-)

**Comment by patrick-nw** [comment]
Perhaps this would be better moved to the "presentations" repo? That one is about the content, right? And docker-present is about the display of that content?

**Comment by katieannemills** [comment]
sorry I missed this - resolved in https://github.com/docker-training/presentations/pull/1130
