### ISSUE TITLE
Can't pull training/docker-present:latest

### ISSUE THREAD

**Issue by stevear22** [docker-training/docker-present#26]
There is no image tagged 'latest' in that registry.  Need to either update the registry to tag one of the image with latest or update the readme file in this repo to have it explicitly target a version - ie:
➤ docker pull training/docker-present:17.06-v1.7
17.06-v1.7: Pulling from training/docker-present
ef0380f84d05: Pull complete
...

**Comment by gnschenker** [comment]
Hi @stevear22 . This is on purpose. We want trainers to be explicit in what they're using. Is there any reason why this wouldn't work for you? Please let us know otherwise I will close this issue.

**Comment by stevear22** [comment]
Thank you
