### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by astropanic** [docker-training/docker-present#8]
~~~bash
docker pull training/docker-present
Using default tag: latest
Pulling repository docker.io/training/docker-present
Error: image training/docker-present:latest not found
~~~

[docker-present](https://hub.docker.com/r/training/docker-present/) image is missing on DockerHub.

Please see https://github.com/docker-training/presentations/issues/44

**Comment by katieannemills** [comment]
This image is now private; ATPs can send their Dockerhub and GitHub ID to training@docker.com to get access.
